/**
 * Database row types — manually maintained to match supabase/migrations/001_initial_schema.sql.
 *
 * Do not add auth-related tables here.  RLS policies are not applied in this
 * project; the service-role key is used for all server-side queries.
 */

export interface DbSession {
  id: string;
  started_at: string;
  last_activity_at: string;
  client_ip: string | null;
  client_geo: Record<string, unknown> | null;
  client_user_agent: string | null;
  email_sent: boolean;
}

export interface DbMessage {
  id: string;
  session_id: string;
  /** "user" | "assistant" */
  role: string;
  /** Plain text content for the transcript view. */
  content: string;
  /** Serialized thinking blocks for analysis.  Null when extended thinking is off. */
  thinking: string | null;
  created_at: string;
}

export interface DbFeedback {
  id: string;
  session_id: string;
  /** 1–5 star rating.  Null if the user left a comment without rating. */
  rating: number | null;
  comment: string | null;
  created_at: string;
}

/** Insert payloads — id and created_at are generated by the database. */
export type DbSessionInsert = Omit<DbSession, "id" | "started_at" | "last_activity_at"> &
  Partial<Pick<DbSession, "started_at" | "last_activity_at">>;

export type DbMessageInsert = Omit<DbMessage, "id" | "created_at">;

export type DbFeedbackInsert = Omit<DbFeedback, "id" | "created_at">;

/** Update payloads — all fields optional except the primary key. */
export type DbSessionUpdate = Partial<Omit<DbSession, "id">>;
