/**
 * Database row types — manually maintained to match the full migration set in supabase/migrations/.
 *
 * Do not add auth-related tables here.  RLS policies are not applied in this
 * project; the service-role key is used for all server-side queries.
 */

export interface DbSession {
  id: string;
  started_at: string;
  last_activity_at: string;
  ended_at: string | null;
  client_ip: string | null;
  client_geo: Record<string, unknown> | null;
  client_user_agent: string | null;
  email_sent: boolean;
  /** Cumulative input tokens across all turns in this session. */
  total_input_tokens: number;
  /** Cumulative output tokens across all turns in this session. */
  total_output_tokens: number;
}

export interface DbMessage {
  id: string;
  session_id: string;
  /** "user" | "assistant" */
  role: string;
  /** Plain text content for the transcript view. */
  content: string;
  /** Serialized thinking blocks for analysis.  Null when extended thinking is off. */
  thinking: string | null;
  /** Input tokens consumed by this API call.  Null for user messages and legacy rows. */
  input_tokens: number | null;
  /** Output tokens produced by this API call.  Null for user messages and legacy rows. */
  output_tokens: number | null;
  created_at: string;
}

export interface DbSessionFeedback {
  id: string;
  session_id: string;
  /** 'student' | 'timeout' */
  source: string;
  /** 'solved' | 'partial' | 'stuck' | null */
  outcome: string | null;
  /** 'positive' | 'neutral' | 'negative' | null */
  experience: string | null;
  comment: string | null;
  skipped: boolean;
  created_at: string;
}

export interface DbSessionFeedbackInsert {
  session_id: string;
  source: string;
  outcome?: string | null;
  experience?: string | null;
  comment?: string | null;
  skipped?: boolean;
}

export interface DbSessionEvaluation {
  id: string;
  session_id: string;
  model: string;
  /** Legacy v6 columns — retained for historical rows, null for new v7 evaluations. */
  opening_sequence: string | null;
  one_question: string;
  asked_why: string | null;
  worked_at_edge: string;
  parallel_problems: string;
  step_feedback: string;
  never_gave_answer: string;
  clarity: string | null;
  tone: string | null;
  resolution: string;
  has_failures: boolean;
  rationale: Record<string, string>;
  /** v7 dimension columns — null for legacy rows. */
  mode_handling: string | null;
  problem_confirmation: string | null;
  probe_reasoning: string | null;
  understood_where_student_was: string | null;
  followed_student_lead: string | null;
  adaptive_tone: string | null;
  created_at: string;
}

export interface DbSessionEvaluationInsert {
  session_id: string;
  model: string;
  /** Legacy v6 columns — omit for new v7 evaluations. */
  opening_sequence?: string | null;
  one_question: string;
  asked_why?: string | null;
  worked_at_edge: string;
  parallel_problems: string;
  step_feedback: string;
  never_gave_answer: string;
  clarity?: string | null;
  tone?: string | null;
  resolution: string;
  has_failures: boolean;
  rationale: Record<string, string>;
  /** v7 dimension columns. */
  mode_handling?: string | null;
  problem_confirmation?: string | null;
  probe_reasoning?: string | null;
  understood_where_student_was?: string | null;
  followed_student_lead?: string | null;
  adaptive_tone?: string | null;
}

/** Insert payloads — id and created_at are generated by the database. */
export type DbSessionInsert =
  Omit<DbSession, "id" | "started_at" | "last_activity_at" | "ended_at" | "total_input_tokens" | "total_output_tokens"> &
  Partial<Pick<DbSession, "id" | "started_at" | "last_activity_at" | "total_input_tokens" | "total_output_tokens">>;

export type DbMessageInsert = Omit<DbMessage, "id" | "created_at">;

/** Update payloads — all fields optional except the primary key. */
export type DbSessionUpdate = Partial<Omit<DbSession, "id">>;

export interface DbDisclaimerAcceptance {
  id: string;
  accepted_at: string;
  client_ip: string | null;
  client_geo: Record<string, unknown> | null;
  client_user_agent: string | null;
  /** FK → sessions(id).  Null until backfilled after first chat message. */
  session_id: string | null;
  /** The client-generated session UUID stored at acceptance time (no FK).
   *  Used to backfill session_id after the sessions row is created. */
  client_session_id: string | null;
  /** Email submitted through the access-wall overlay.  Added in migration 011. */
  email: string | null;
}

export interface DbDisclaimerAcceptanceInsert {
  client_ip?: string | null;
  client_geo?: Record<string, unknown> | null;
  client_user_agent?: string | null;
  session_id?: string | null;
  client_session_id?: string | null;
  email?: string | null;
}
