/**
 * Database row types — manually maintained to match supabase/migrations/.
 *
 * RLS is enabled on these tables (migration 005). The server uses the
 * service-role key and bypasses RLS; direct client queries via the anon
 * key are filtered by `auth.uid()` policies.
 */

export interface DbSession {
  id: string;
  started_at: string;
  last_activity_at: string;
  ended_at: string | null;
  client_ip: string | null;
  client_geo: Record<string, unknown> | null;
  client_user_agent: string | null;
  email_sent: boolean;
  /** Cumulative input tokens across all turns in this session. */
  total_input_tokens: number;
  /** Cumulative output tokens across all turns in this session. */
  total_output_tokens: number;
  /** Claude model ID used for this session (e.g. "claude-sonnet-4-6"). Set on first message. */
  model: string | null;
  /** Tutor prompt filename stem used for this session (e.g. "tutor-prompt-v7"). Set on first message. */
  prompt_name: string | null;
  /** Whether extended thinking was enabled for this session. Defaults to true at the DB level. */
  extended_thinking: boolean;
  /** Supabase auth.users.id — required (migration 005). */
  user_id: string;
  /** Whether the session has been run through automated evaluation. Defaults to false (migration 006). */
  evaluated: boolean;
}

export interface DbMessage {
  id: string;
  session_id: string;
  /** "user" | "assistant" */
  role: string;
  /** Plain text content for the transcript view. */
  content: string;
  /** Serialized thinking blocks for analysis.  Null when extended thinking is off. */
  thinking: string | null;
  /** Input tokens consumed by this API call.  Null for user messages. */
  input_tokens: number | null;
  /** Output tokens produced by this API call.  Null for user messages. */
  output_tokens: number | null;
  created_at: string;
}

export interface DbSessionFeedback {
  id: string;
  session_id: string;
  /** 'student' | 'timeout' */
  source: string;
  /** 'solved' | 'partial' | 'stuck' | null */
  outcome: string | null;
  /** 'positive' | 'neutral' | 'negative' | null */
  experience: string | null;
  comment: string | null;
  skipped: boolean;
  created_at: string;
}

export interface DbSessionFeedbackInsert {
  session_id: string;
  source: string;
  outcome?: string | null;
  experience?: string | null;
  comment?: string | null;
  skipped?: boolean;
}

export interface DbSessionEvaluation {
  id: string;
  session_id: string;
  model: string;
  mode_handling: string | null;
  problem_confirmation: string | null;
  never_gave_answer: string;
  probe_reasoning: string | null;
  understood_where_student_was: string | null;
  one_question: string;
  worked_at_edge: string;
  followed_student_lead: string | null;
  adaptive_tone: string | null;
  parallel_problems: string;
  step_feedback: string;
  resolution: string;
  has_failures: boolean;
  rationale: Record<string, string>;
  created_at: string;
}

export interface DbSessionEvaluationInsert {
  session_id: string;
  model: string;
  mode_handling?: string | null;
  problem_confirmation?: string | null;
  never_gave_answer: string;
  probe_reasoning?: string | null;
  understood_where_student_was?: string | null;
  one_question: string;
  worked_at_edge: string;
  followed_student_lead?: string | null;
  adaptive_tone?: string | null;
  parallel_problems: string;
  step_feedback: string;
  resolution: string;
  has_failures: boolean;
  rationale: Record<string, string>;
}

/** Insert payloads — id and created_at are generated by the database. */
export type DbSessionInsert =
  Omit<DbSession, "id" | "started_at" | "last_activity_at" | "ended_at" | "total_input_tokens" | "total_output_tokens" | "model" | "prompt_name" | "extended_thinking" | "evaluated"> &
  Partial<Pick<DbSession, "id" | "started_at" | "last_activity_at" | "total_input_tokens" | "total_output_tokens" | "model" | "prompt_name" | "extended_thinking" | "evaluated">>;

export type DbMessageInsert = Omit<DbMessage, "id" | "created_at">;

/** Update payloads — all fields optional except the primary key. */
export type DbSessionUpdate = Partial<Omit<DbSession, "id">>;
